Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,10 +24,6 @@ jobs:
           python3 -m venv venv
           source venv/bin/activate
           
-      
-  # deploy:
-  #   runs-on: ubuntu-latest
-  #   steps:
       - name: Install Dependencies
         run: |
           python -m pip install --upgrade pip
@@ -36,12 +32,18 @@ jobs:
       - name: Run Unit Tests
         run: |
           python3 -m unittest test_app.py
-          
-      - name: Deploy App
-        run: python -m flask --version  # Simple test
-
-      - name: Run Gunicorn
+            
+      - name: Deploy Flask Application
         run: |
            ls
            nohup python3 app.py
+           
+      - name: health check
+        run: |
+          for i in {1..10}; do
+            curl -s -o /dev/null -w "%{http_code}" http://52.91.51.113:5000/ | grep "200" && echo "Health check passed" && exit 0 || echo "Waiting for service..."; 
+            sleep 5; 
+          done; 
+          echo "Health check failed" && exit 1
+         
 
