Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -49,6 +49,6 @@ jobs:
   #       run: |
   #         for i in {1..10}; do
   #           curl -s -o /dev/null -w "%{http_code}" http://52.91.51.113:5000/ | grep "200" && echo "Health check passed" && exit 0 || echo "Waiting for service...";
-            sleep 5;
-          done;
-          echo "Health check failed" && exit 1
+          #   sleep 5;
+          # done;
+          # echo "Health check failed" && exit 1
