deploy the python application

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,7 +10,7 @@ env:
 
 jobs:
   Build-test-deploy:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
 
     steps:
       - name: Checkout Code
@@ -39,12 +39,8 @@ jobs:
       - name: Deploy Flask Application
         run: |
           nohup python3 app.py &
+          sleep 60
 
-  health:
-    needs: "Build-test-deploy"
-    runs-on: self-hosted
-
-    steps:
       - name: Health check
         run: |
           for i in {1..10}; do
@@ -52,5 +48,18 @@ jobs:
             sleep 5;
           done;
           echo "Health check is failed***" && exit 1
+
+  # health:
+  #   needs: "Build-test-deploy"
+  #   runs-on: ubuntu-latest
+
+  #   steps:
+  #     - name: Health check
+  #       run: |
+  #         for i in {1..10}; do
+  #           curl -s -o /dev/null -w "%{http_code}" $HEALTHCHECK_URL | grep "200" && echo "Health check passed" && exit 0 || echo "Waiting for service...";
+  #           sleep 5;
+  #         done;
+  #         echo "Health check is failed***" && exit 1
           
           
